import models.App
import utility.extension.convertSizeToMegabyte
import utility.extension.convertStringToDateObject

class FakeData {

    val fakeApps= listOf(
        App(
            name = "App 1",
            company = "Google",
            category = "Libraries & Demo",
            updatedAt = "November 13 2019".convertStringToDateObject(),
            size = "5.0M".convertSizeToMegabyte(),
            installsCount = 5,
            currentVersion = "1",
            requiresAndroid = 4.4,
        ),
        App(
            name = "App 2",
            company = "Google LLC",
            category = "Medical",
            updatedAt = "September 26 2017".convertStringToDateObject(),
            size = "22M".convertSizeToMegabyte(),
            installsCount = 100000,
            currentVersion = "1.4.4-0e73d19a",
            requiresAndroid = 7.0,
        ),
        App(
            name = "App 3",
            company = "Clipto Team",
            category = "Productivity",
            updatedAt = "December 24 2021".convertStringToDateObject(),
            size = "28M".convertSizeToMegabyte(),
            installsCount = 100000,
            currentVersion = "6.0.16-release",
            requiresAndroid = 5.0,
        ),
        App(
            name = "App 4",
            company = "Pazu Games",
            category =  "Medical",
            updatedAt = "December 15 2021".convertStringToDateObject(),
            size = "42M".convertSizeToMegabyte(),
            installsCount = 100000,
            currentVersion = "1.4.4-0e73d19a",
            requiresAndroid = 7.0,
        ),
        App(
            name = "App 5",
            company = "Weedmaps",
            category = "Medical",
            updatedAt = "March 4 2022".convertStringToDateObject(),
            size = "1.1G".convertSizeToMegabyte(),
            installsCount = 1800000,
            currentVersion = "7.0.2",
            requiresAndroid = 5.0,
        ),
        App(
            name = "App 6",
            company = "Craigpark Limited",
            category = "Productivity",
            updatedAt = "April 6 2022".convertStringToDateObject(),
            size = "63M".convertSizeToMegabyte(),
            installsCount = 5000000,
            currentVersion = "14.18.0.36314",
            requiresAndroid = 5.0,
        ),
        App(
            name = "App 7",
            company = "WhatsApp LLC",
            category = "Communication",
            updatedAt = "May 9 2022".convertStringToDateObject(),
            size = "800M".convertSizeToMegabyte(),
            installsCount = 5000000000,
            currentVersion = "2.22.10.73",
            requiresAndroid = 4.1,
        ),
        App(
            name = "App 8",
            company = "Google LLC",
            category = "Tools",
            updatedAt = "May 12 2022".convertStringToDateObject(),
            size = "28M".convertSizeToMegabyte(),
            installsCount = 100000,
            currentVersion = "Varies with device",
            requiresAndroid = 9.1,
        ),
        App(
            name = "App 9",
            company = "WhatsApp LLC",
            category = "Communication",
            updatedAt = "December 15 2021".convertStringToDateObject(),
            size = "42M".convertSizeToMegabyte(),
            installsCount = 5000000,
            currentVersion = "Varies with device",
            requiresAndroid = 7.0,
        ),
        App(
            name = "App 10",
            company = "Area 120 by Google",
            category = "Casual",
            updatedAt = "May 10 2022".convertStringToDateObject(),
            size = "117M".convertSizeToMegabyte(),
            installsCount = 1800000,
            currentVersion = "8.5.0g",
            requiresAndroid = 5.0,

            ),
        App(
            name = "App 11",
            company = "Azur Interactive Games Limited",
            category = "Action",
            updatedAt = "January 25 2022".convertStringToDateObject(),
            size = "87M".convertSizeToMegabyte(),
            installsCount = 10000000,
            currentVersion = "0.17.1",
            requiresAndroid = 9.1,
        ),
        App(
            name = "App 12",
            company = "Vidma Video Studio",
            category = "Video Players & Editors",
            updatedAt = "May 19 2022".convertStringToDateObject(),
            size = "64M".convertSizeToMegabyte(),
            installsCount = 1000000,
            currentVersion = "1.16.2",
            requiresAndroid = 9.1,
        ),
        App(
            name = "App 13",
            company = "AIBY Inc.",
            category = "Education",
            updatedAt = "May 13 2022".convertStringToDateObject(),
            size = "37M".convertSizeToMegabyte(),
            installsCount = 1000000,
            currentVersion = "2.25.4",
            requiresAndroid = 9.0,
        ),
        App(
            name = "App 14",
            company = "Pazu Games",
            category = "Medical",
            updatedAt = "December 15 2021".convertStringToDateObject(),
            size = "42M".convertSizeToMegabyte(),
            installsCount = 100000,
            currentVersion = "1.4.4-0e73d19a",
            requiresAndroid = 7.0,
        ),
        App(
            name = "App 15",
            company = "Weedmaps",
            category = "Medical",
            updatedAt = "March 4 2022".convertStringToDateObject(),
            size = "9.6M".convertSizeToMegabyte(),
            installsCount = 1000000,
            currentVersion = "7.0.2",
            requiresAndroid = 5.0,

            ),
        App(
            name = "App 16",
            company = "Craigpark Limited",
            category = "Productivity",
            updatedAt = "April 17 2022".convertStringToDateObject(),
            size = "Varies with device".convertSizeToMegabyte(),
            installsCount = 1000000,
            currentVersion = "5.3.5",
            requiresAndroid = 5.0,
        ),
        App(
            name = "App 17",
            company = "WhatsApp LLC",
            category = "Communication",
            updatedAt = "May 9 2022".convertStringToDateObject(),
            size = "800M".convertSizeToMegabyte(),
            installsCount = 5000000000,
            currentVersion = "2.22.10.73",
            requiresAndroid = 4.1,
        ),
        App(
            name = "App 18",
            company = "Game Insight",
            category = "Action",
            updatedAt = "May 12 2022".convertStringToDateObject(),
            size = "1.1G".convertSizeToMegabyte(),
            installsCount = 50000000,
            currentVersion = "30.0.271",
            requiresAndroid = 5.0,
        ),
        App(
            name = "App 19",
            company = "TIMEFLIK (ex MR TIME)",
            category = "Personalization",
            updatedAt = "December 15 2021".convertStringToDateObject(),
            size = "4.7M".convertSizeToMegabyte(),
            installsCount = 5000000,
            currentVersion = "10, 1.0.0",
            requiresAndroid = 9.0,
        ),
        App(
            name = "App 20",
            company = "Area 120 by Google",
            category = "Personalization",
            updatedAt = "August 18 2021".convertStringToDateObject(),
            size = "117M".convertSizeToMegabyte(),
            installsCount = 10,
            currentVersion = "8.5.0g",
            requiresAndroid = 5.0,
        ),
    )

}